services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    restart: always
    volumes:
      - ./consul/config/consul.json:/consul/config/consul.json
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command:
      - "agent"
      - "-config-dir=/consul/config"

  gateway:
    build: ./gateway
    container_name: gateway
    restart: always
    ports:
      - "8010:8010"

  service-a:
    build: ./service_A
    container_name: sa_container
    restart: always
    ports:
      - "8020:8020"
