spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: 779059902284-ojrhrohupddjgqc1f7p9heimru22e38u.apps.googleusercontent.com
            client-secret: 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
  cloud:
    consul:
      host: consul
      port: 8500
    gateway:
      routes:
        - id: "A"
          uri: "lb://service-a"
          predicates:
            - "Path=/s-a/**"
        - id: "C"
          uri: "lb://service-c"
          predicates:
            - "Path=/s-c/**"
          filters:
            - "TokenRelay="
            - "RemoveRequestHeader=Cookie"
server:
  port: 8010
