spring:
  application:
    name: gateway-local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 779059902284-ojrhrohupddjgqc1f7p9heimru22e38u.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
  cloud:
    consul:
      host: localhost
#      host: consul
      port: 8500
    gateway:
      routes:
        - id: "A"
#          uri: "http://localhost:8020"
          uri: "lb://service-a"
          predicates:
            - "Path=/s-a/**"
        - id: "B"
          uri: "http://localhost:8030"
#          uri: "lb://service-b"
          predicates:
            - "Path=/s-b/**"
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
server:
  port: 8010
