spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            clientId: 779059902284-ojrhrohupddjgqc1f7p9heimru22e38u.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:9400/login/oauth2/code/google
            authorizedGrantTypes: authorization_code
            scope: openid,profile,email
  cloud:
    consul:
      host: consul
      port: 8500
    gateway:
      routes:
        - id: "A"
          uri: "lb://service-a"
          predicates:
            - "Path=/s-a/**"
        - id: "C"
          uri: "lb://service-c"
          predicates:
            - "Path=/s-c/**"
          filters:
            - "TokenRelay="
server:
  port: 8010
