spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: 779059902284-ojrhrohupddjgqc1f7p9heimru22e38u.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:9400/login/oauth2/code/google
            authorized-grant-types: authorization_code
            scope: openid,profile,email
#          github:
#            provider: github
#            client-id: 049f346e072733454a32
#            client-secret: 197af9740f4c3f2165847168e207998a3e8e1749
  cloud:
    consul:
      host: consul
      port: 8500
    gateway:
      routes:
        - id: "A"
          uri: "lb://service-a"
          predicates:
            - "Path=/s-a/**"
        - id: "C"
          uri: "lb://service-c"
          predicates:
            - "Path=/s-c/**"
          filters:
            - "FetchJwtFromAccessToken"
#            - "TokenRelay="
server:
  port: 8010
