server:
  port: 8010
spring:
  application:
    name: gateway
  cloud:
    consul:
#      host: localhost
      host: consul
      port: 8500
    gateway:
      routes:
      - id: "A"
#        uri: "http://localhost:8020"
        uri: "lb://service-a"
        predicates:
        - "Path=/s-a/**"
