spring:
  application:
    name: service-c
  security:
    oauth2:
      resourceserver:
          jwt:
            issuer-uri: https://accounts.google.com
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    consul:
      host: consul
      port: 8500

interceptor:
    header: "Authorization"
    tokenType: "Bearer"
user:
  details:
    id: "sub"
    name: "given_name"
    surname: "family_name"
    email: "email"
server:
  port: 8040
