spring:
  application:
    name: service-a
  cloud:
    loadbalancer:
      enabled: false
    consul:
#      host: localhost
      host: consul
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.int}
server:
  port: 8020
greeting:
  message: "Hello from microservices CI-27 test!"

